CREATE TABLE strategy_envs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    alias TEXT NOT NULL UNIQUE,
    db_schema TEXT NOT NULL UNIQUE
        CHECK (db_schema ~ '^[a-z][a-z0-9_]*$'),
    host TEXT NOT NULL,
    env_path TEXT NOT NULL,
    csv_output_dir TEXT NOT NULL,
    exchange TEXT NOT NULL,
    account_mode TEXT NOT NULL,
    strategy_kind TEXT NOT NULL,
    required_keys JSONB NOT NULL
        CHECK (jsonb_typeof(required_keys) = 'array'),
    config_url TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (host, env_path)
);

CREATE INDEX idx_strategy_envs_enabled_order
    ON strategy_envs(enabled, sort_order);

INSERT INTO strategy_envs (
    slug, alias, db_schema, host, env_path, csv_output_dir,
    exchange, account_mode, strategy_kind, required_keys, config_url, sort_order
)
VALUES
    (
        'binance_mm_alpha', 'binance做市', 'binance_mm_alpha', 'local',
        '/home/ubuntu/binance_mm_alpha/env.sh',
        '/home/ubuntu/liang_torch/making_market_analysis/binanceswap_mm_ltp',
        'binance', 'usdm_futures', 'market_making',
        '["BINANCE_API_KEY", "BINANCE_API_SECRET"]'::jsonb,
        '/mm/binance_mm_alpha/config', 10
    ),
    (
        'bybit_mm_alpha', 'bybit做市', 'bybit_mm_alpha', 'sg',
        '/home/ubuntu/bybit_mm_alpha/env.sh',
        '/home/ubuntu/liang_torch/making_market_analysis/mm_trades_bybit_ltp',
        'bybit', 'unified', 'market_making',
        '["BYBIT_API_KEY", "BYBIT_API_SECRET"]'::jsonb,
        '/mm/bybit_mm_alpha/config', 20
    ),
    (
        'binance-intra-arb01', 'binance mt', 'binance_intra_arb01', 'local',
        '/home/ubuntu/binance-intra-arb01/env.sh',
        '/home/ubuntu/liang_torch/spotswap_arb_analysis_archive_20260526/binance_basis_arbitrage_subaccount_data',
        'binance', 'usdm_futures', 'intra_exchange',
        '["BINANCE_API_KEY", "BINANCE_API_SECRET"]'::jsonb,
        '/intra/binance-intra-arb01/config', 30
    ),
    (
        'bybit-intra-arb01', 'bybit mt', 'bybit_intra_arb01', 'sg',
        '/home/ubuntu/bybit-intra-arb01/env.sh',
        '/home/ubuntu/liang_torch/binance_fr/bybit_spot_swap_arb02',
        'bybit', 'unified', 'intra_exchange',
        '["BYBIT_API_KEY", "BYBIT_API_SECRET"]'::jsonb,
        '/intra/bybit-intra-arb01/config', 40
    ),
    (
        'bybit-intra-arb02', 'bybit cta', 'bybit_intra_arb02', 'sg',
        '/home/ubuntu/bybit-intra-arb02/env.sh',
        '/home/ubuntu/liang_torch/binance_fr/bybit_spot_swap_cta01',
        'bybit', 'unified', 'cta',
        '["BYBIT_API_KEY", "BYBIT_API_SECRET"]'::jsonb,
        '/intra/bybit-intra-arb02/config', 50
    ),
    (
        'binance_fr_arb04', 'binance 外部资金', 'binance_fr_arb04', 'local',
        '/home/ubuntu/binance_fr_arb04/env.sh',
        '/home/ubuntu/liang_torch/binance_fr/binance_ltp_trades01',
        'binance', 'portfolio_margin', 'funding_rate',
        '["BINANCE_API_KEY", "BINANCE_API_SECRET"]'::jsonb,
        '/fr/binance_fr_arb04/config', 60
    ),
    (
        'binance_fr_arb02', 'binance nova01', 'binance_fr_arb02', 'local',
        '/home/ubuntu/binance_fr_arb02/env.sh',
        '/home/ubuntu/liang_torch/binance_fr/binance_trades_new',
        'binance', 'portfolio_margin', 'funding_rate',
        '["BINANCE_API_KEY", "BINANCE_API_SECRET"]'::jsonb,
        '/fr/binance_fr_arb02/config', 70
    ),
    (
        'binance_fr_arb01', 'binance nova02', 'binance_fr_arb01', 'local',
        '/home/ubuntu/binance_fr_arb01/env.sh',
        '/home/ubuntu/liang_torch/binance_fr/binance_trades_nova02',
        'binance', 'portfolio_margin', 'funding_rate',
        '["BINANCE_API_KEY", "BINANCE_API_SECRET"]'::jsonb,
        '/fr/binance_fr_arb01/config', 80
    ),
    (
        'binance_fr_arb03', 'binance 资费自营', 'binance_fr_arb03', 'local',
        '/home/ubuntu/binance_fr_arb03/env.sh',
        '/home/ubuntu/liang_torch/binance_fr/binance_trades',
        'binance', 'portfolio_margin', 'funding_rate',
        '["BINANCE_API_KEY", "BINANCE_API_SECRET"]'::jsonb,
        '/fr/binance_fr_arb03/config', 90
    ),
    (
        'gate_fr_arb02', 'gate资费外部资金', 'gate_fr_arb02', 'local',
        '/home/ubuntu/gate_fr_arb02/env.sh',
        '/home/ubuntu/liang_torch/funding_rate_analysis/fr_data_ltp_gate02',
        'gate', 'unified', 'funding_rate',
        '["GATE_API_KEY", "GATE_API_SECRET"]'::jsonb,
        '/fr/gate_fr_arb02/config', 100
    ),
    (
        'bitget_fr_arb02', 'bitget 资费自营', 'bitget_fr_arb02', 'local',
        '/home/ubuntu/bitget_fr_arb02/env.sh',
        '/home/ubuntu/liang_torch/funding_rate_analysis/fr_data_ltp_bitget',
        'bitget', 'unified', 'funding_rate',
        '["BITGET_API_KEY", "BITGET_API_SECRET", "BITGET_API_PASSPHRASE"]'::jsonb,
        '/fr/bitget_fr_arb02/config', 110
    ),
    (
        'gate_fr_arb01', 'gate 资费自营', 'gate_fr_arb01', 'local',
        '/home/ubuntu/gate_fr_arb01/env.sh',
        '/home/ubuntu/liang_torch/funding_rate_analysis/fr_data_ltp_gate',
        'gate', 'unified', 'funding_rate',
        '["GATE_API_KEY", "GATE_API_SECRET"]'::jsonb,
        '/fr/gate_fr_arb01/config', 120
    );

CREATE OR REPLACE FUNCTION ensure_strategy_storage(target_schema TEXT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    IF target_schema !~ '^[a-z][a-z0-9_]*$' THEN
        RAISE EXCEPTION 'invalid strategy schema: %', target_schema;
    END IF;

    EXECUTE format('CREATE SCHEMA IF NOT EXISTS %I', target_schema);

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS %I.trade_fills (
            market TEXT NOT NULL,
            symbol TEXT NOT NULL,
            trade_id TEXT NOT NULL,
            order_id TEXT,
            side TEXT,
            liquidity_role TEXT,
            price NUMERIC(38, 18) NOT NULL,
            quantity NUMERIC(38, 18) NOT NULL,
            quote_quantity NUMERIC(38, 18),
            fee_amount NUMERIC(38, 18),
            fee_asset TEXT,
            fee_usdt NUMERIC(38, 18),
            realized_pnl NUMERIC(38, 18),
            event_time_ms BIGINT NOT NULL CHECK (event_time_ms >= 0),
            raw JSONB NOT NULL,
            fetched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (market, symbol, trade_id)
        )',
        target_schema
    );

    EXECUTE format(
        'CREATE INDEX IF NOT EXISTS %I ON %I.trade_fills (event_time_ms)',
        target_schema || '_trade_fills_time_idx',
        target_schema
    );

    EXECUTE format(
        'CREATE INDEX IF NOT EXISTS %I ON %I.trade_fills (symbol, event_time_ms)',
        target_schema || '_trade_fills_symbol_time_idx',
        target_schema
    );

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS %I.funding_fees (
            record_id TEXT PRIMARY KEY,
            symbol TEXT,
            asset TEXT,
            amount NUMERIC(38, 18) NOT NULL,
            amount_usdt NUMERIC(38, 18),
            funding_rate NUMERIC(38, 18),
            event_time_ms BIGINT NOT NULL CHECK (event_time_ms >= 0),
            raw JSONB NOT NULL,
            fetched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )',
        target_schema
    );

    EXECUTE format(
        'CREATE INDEX IF NOT EXISTS %I ON %I.funding_fees (event_time_ms)',
        target_schema || '_funding_fees_time_idx',
        target_schema
    );

    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS %I.borrow_interest (
            record_id TEXT PRIMARY KEY,
            symbol TEXT,
            asset TEXT NOT NULL,
            amount NUMERIC(38, 18) NOT NULL,
            amount_usdt NUMERIC(38, 18),
            interest_rate NUMERIC(38, 18),
            event_time_ms BIGINT NOT NULL CHECK (event_time_ms >= 0),
            raw JSONB NOT NULL,
            fetched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )',
        target_schema
    );

    EXECUTE format(
        'CREATE INDEX IF NOT EXISTS %I ON %I.borrow_interest (event_time_ms)',
        target_schema || '_borrow_interest_time_idx',
        target_schema
    );
END;
$$;

SELECT ensure_strategy_storage(db_schema)
FROM strategy_envs
ORDER BY sort_order;
